export {
    createHandshakeClient,
    type HandshakeTransport,
    type HandshakeClientConfig,
    type EstablishedSession,
} from "./client.js";

export {
    bufToHex,
    importServerRSAKey,
    generateClientNonce,
    buildStage1Packet,
    parseStage1Response,
    verifyServerSignature,
    buildStage1PacketV2,
    parseStage1ResponseV2,
    generateECDHKeyPair,
    buildStage2Packet,
    buildStage2PacketV2,
    parseStage2ResponseV2,
    verifyTranscriptSignature,
    deriveDirectionalAESKeys,
    deriveSharedAESKey,
    encryptSecure,
    decryptSecure,
    importAsHMACKey,
    computeResumeProof,
    type ECDHKeyPair,
    type DerivedDirectionalAESKeys,
    type DerivedAESKey,
} from "./handshake.js";
